<br>
<div class="border border-warning">
    <ul class="list-group">
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminusers/add"><img src="<?php echo URLROOT; ?>/assets/images/admin/adduser.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("Add User"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminusers/advancedsearch"><img src="<?php echo URLROOT; ?>/assets/images/admin/user_search.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("ADVANCED_USER_SEARCH"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminavatar"><img src="<?php echo URLROOT; ?>/assets/images/admin/avatar_log.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("AVATAR_LOG"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminbackup"><img src="<?php echo URLROOT; ?>/assets/images/admin/db_backup.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("BACKUPS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminbans/ip"><img src="<?php echo URLROOT; ?>/assets/images/admin/ip_block.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("BANNED_IPS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminbans/torrent"><img src="<?php echo URLROOT; ?>/assets/images/admin/banned_torrents.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("BANNED_TORRENTS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminblocks"><img src="<?php echo URLROOT; ?>/assets/images/admin/blocks.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("BLOCKS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminclient"><img src="<?php echo URLROOT; ?>/assets/images/admin/client.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Client Ban</b></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/Adminusers/cheats"><img src="<?php echo URLROOT; ?>/assets/images/admin/cheats.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("Detect Cheats"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/Adminusers/duplicateip"><img src="<?php echo URLROOT; ?>/assets/images/admin/double-ip.ico" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("DUPLICATEIP"); ?></b></a></li> 
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminbans/email"><img src="<?php echo URLROOT; ?>/assets/images/admin/mail_bans.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("EMAIL_BANS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminfaq"><img src="<?php echo URLROOT; ?>/assets/images/admin/faq.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("FAQ"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminforum"><img src="<?php echo URLROOT; ?>/assets/images/admin/forums.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("FORUM_MANAGEMENT"); ?></b></a></li>
	<li class="list-group-item"><a href="<?php echo URLROOT; ?>/admintorrent/free"><img src="<?php echo URLROOT; ?>/assets/images/admin/free_leech.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Freeleech Torrents</b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/Adminsnatched"><img src="<?php echo URLROOT; ?>/assets/images/hitnrun.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Hit & Runs</b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/admincomments"><img src="assets/images/admin/comments.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("LATEST_COMMENTS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminmessages/mass"><img src="<?php echo URLROOT; ?>/assets/images/admin/mass_pm.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("MASS_PM"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminmessages"><img src="<?php echo URLROOT; ?>/assets/images/admin/message_spy.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("MESSAGE_SPY"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminnews"><img src="<?php echo URLROOT; ?>/assets/images/admin/news.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("NEWS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/adminpeers"><img src="<?php echo URLROOT; ?>/assets/images/admin/peer_list.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo Lang::T("PEERS_LIST"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo URLROOT; ?>/Admininvites"><img src="<?php echo URLROOT; ?>/assets/images/admin/invited_user.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Invited Users</b></a></li>   
    </ul>
</div>